In [18]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

b = np.linalg.inv(a @ a.T)

c = np.array([[1, 2], [3, 4]])
d = np.linalg.inv(c)

print(a)
print(a.T)
print(b)
print(a.T @ a)
print(c)
print(d)

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[ 0.54375 -0.21875]
 [-0.21875  0.09375]]
[[26 32 38 44]
 [32 40 48 56]
 [38 48 58 68]
 [44 56 68 80]]
[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [19]:
A = np.array([
    [1, 2, 6],
    [1, 4, 5],
    [1, 6, 7]
])

B = np.array([50, 60, 80])

r_cap = np.linalg.inv(A.T @ A) @ A.T @ B

print(r_cap)

[16.66666667  6.66666667  3.33333333]


In [21]:
matrix = np.array([
    [0, 0, 3],
    [0, 0, 0],
    [1, 0, 0]
])

zero_count = np.sum(matrix==0)
total_elements = matrix.size

if zero_count > total_elements/2:
    print('Sparse matrix')
else:
    print('Not a sparse matrix')

Sparse matrix


In [25]:
rows, cols = matrix.shape
sparse_representation = []

for i in range(rows):
    for j in range(cols):
        if matrix[i][j]!=0:
            sparse_representation.append((i, j, int(matrix[i][j])))

print(sparse_representation)

[(0, 2, 3), (2, 0, 1)]


In [28]:
from scipy.sparse import csr_matrix

A_dense = (csr_matrix(sparse_representation)).toarray()

In [29]:
A_dense

array([[0, 2, 3],
       [2, 0, 1]])

In [31]:
from sklearn.feature_extraction.text import CountVectorizer

In [32]:
documents = ['AI ML', 'Data Spam', 'Spam']

In [33]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)

In [34]:
print('Sparse matrix:\n', X)
print('Dense form: \n', X.toarray())

Sparse matrix:
 <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 5 stored elements and shape (3, 4)>
  Coords	Values
  (0, 0)	1
  (0, 2)	1
  (1, 1)	1
  (1, 3)	1
  (2, 3)	1
Dense form: 
 [[1 0 1 0]
 [0 1 0 1]
 [0 0 0 1]]
