In [1]:
nums = input("Enter the numbers separated by spaces").split(" ")
nums = [int(i) for i in nums]

Enter the numbers separated by spaces 12 13 14 15 16 -9 -34 2 -50 -80 100 -99 0 89


In [3]:
import numpy as np

In [8]:
leng = len(nums)
s = sum(nums)
avg = round(s/leng, 3)
avg_nums = [abs(p) for p in nums]
x = np.abs(np.array(nums) - np.array([avg for i in nums]))
print("Average = ", avg)
print("Absolute Average = ", round(sum(list(map(lambda x: abs(x), nums)))/leng, 3))
print("List = ", nums)
print("Absolute Errors = ", x)
print("Mean absolute Error = ", x.mean())

Average =  -0.786
Absolute Average =  38.071
List =  [12, 13, 14, 15, 16, -9, -34, 2, -50, -80, 100, -99, 0, 89]
Absolute Errors =  [ 12.786  13.786  14.786  15.786  16.786   8.214  33.214   2.786  49.214
  79.214 100.786  98.214   0.786  89.786]
Mean absolute Error =  38.296


In [24]:
salaries = np.array([25, 30, 28, 27, 29, 31, 100, 5])
mean_salary = np.mean(salaries)

In [25]:
deviation = np.abs(salaries - mean_salary)
thresholds1 = 1.5*np.mean(deviation)
thresholds2 = 3*np.mean(deviation)

In [26]:
outliers1 = salaries[deviation > thresholds1]
outliers2 = salaries[deviation > thresholds2]

In [27]:
outliers1

array([100,   5])

In [28]:
outliers2

array([100])

In [29]:
thresholds1

np.float64(24.609375)

In [30]:
thresholds2

np.float64(49.21875)

In [31]:
deviation

array([ 9.375,  4.375,  6.375,  7.375,  5.375,  3.375, 65.625, 29.375])

In [32]:
mean_salary

np.float64(34.375)

In [34]:
a = np.array([2, 3, 4])
b = np.array([5, 7, 8])

dist = np.linalg.norm(a-b)
x = sum((a[i] - b[i])**2 for i in range(len(a)))
print(x**0.5)

6.4031242374328485


In [35]:
cust1 = input("Enter the age, salary and spending score for customer 1: ").split(" ")
cust2 = input("Enter the age, salary and spending score for customer 2: ").split(" ")
cust1 = [int(i) for i in cust1]
cust2 = [int(i) for i in cust2]

Enter the age, salary and spending score for customer 1:  45 30000 850
Enter the age, salary and spending score for customer 2:  42 40000 870


In [37]:
cust1 = np.array(cust1)
cust2 = np.array(cust2)

diff = np.linalg.norm(cust1 - cust2)

In [38]:
diff

np.float64(10000.02044997909)