In [1]:
import pandas as pd
import numpy as np

In [11]:
def load_boston():
    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2,:], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]
    return {'data': data, 'target': target}

In [13]:
boston = load_boston()
X = boston['data']
y = boston['target']
A = X[:4, [0,4,5,6]] #CRIM, NOX, RM, AGE
b = y[:4]

In [22]:
x = np.linalg.solve(A, b)

In [23]:
print(x)

[-3.12710043e+02 -1.15193942e+02  1.44996465e+01 -1.13259317e-01]


In [24]:
np.linalg.inv(A.T @ A) @ A.T @ b

array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])

In [26]:
X_w = np.linalg.inv(X.T @ X) @ X.T @ y

In [27]:
X_w

array([-9.28965170e-02,  4.87149552e-02, -4.05997958e-03,  2.85399882e+00,
       -2.86843637e+00,  5.92814778e+00, -7.26933458e-03, -9.68514157e-01,
        1.71151128e-01, -9.39621540e-03, -3.92190926e-01,  1.49056102e-02,
       -4.16304471e-01])

In [28]:

import sympy as sp

In [33]:
x, y, a, b, k = sp.symbols('x y a b k')

In [34]:
fx = x**3 - 1
gx = sp.log(sp.log(x**2 - 3*k))
hx = sp.exp(a*x**b)

In [35]:
sp.diff(fx, x)

3*x**2

In [36]:
sp.diff(gx, x)

2*x/((-3*k + x**2)*log(-3*k + x**2))

In [37]:
sp.diff(hx, x)

a*b*x**b*exp(a*x**b)/x

In [38]:
f = sp.exp(x**2 + 2*y**2)
fx = sp.diff(f, x)
fy = sp.diff(f, y)
fxy = sp.diff(fx, y)
fyx = sp.diff(fy, x)
fxx = sp.diff(fx, x)
fyy = sp.diff(fy, y)

In [39]:
fx

2*x*exp(x**2 + 2*y**2)

In [40]:
fy

4*y*exp(x**2 + 2*y**2)

In [41]:
fxy

8*x*y*exp(x**2 + 2*y**2)

In [42]:
fyx

8*x*y*exp(x**2 + 2*y**2)

In [43]:
fxx

4*x**2*exp(x**2 + 2*y**2) + 2*exp(x**2 + 2*y**2)

In [ ]:
fyy