In [1]:
import numpy as np

In [3]:
image = np.array([
    [0, 50, 100],
    [150, 200, 250],
    [30, 60, 90]
])

In [4]:
print("Original Image: \n", image)

Original Image: 
 [[  0  50 100]
 [150 200 250]
 [ 30  60  90]]


In [11]:
vector = image.flatten()

In [12]:
print("Vector Representation: \n", vector)

Vector Representation: 
 [  0  50 100 150 200 250  30  60  90]


In [13]:
vector

array([  0,  50, 100, 150, 200, 250,  30,  60,  90])

In [14]:
vector.resize((3, 3))

In [15]:
vector

array([[  0,  50, 100],
       [150, 200, 250],
       [ 30,  60,  90]])

In [17]:
x = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

y = [
    [9, 8, 7], 
    [6, 5, 4], 
    [3, 2, 1]
]

result = [[0,0,0], [0,0,0], [0,0,0]]

for i in range(3):
    for j in range(3):
        result[i][j] = x[i][j] + y[i][j]

for r in result:
    print(r)

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


In [18]:
a = np.array(x)
b = np.array(y)
a @ b

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])