In [2]:
import numpy as np

In [3]:
t = np.array([-2, 3, 4, 5, 6])
a = 10
b = 20
# two = np.linspace(a, b, b-a+1)
two = np.arange(a, b+1, 1)
one = np.linspace(a, b, b-a+1)
three = np.full((3, 4), 8)
four = np.ones((4, 4))
five = np.zeros((3, 3))
six = np.random.rand(3, 3)
seven = np.random.randint(10, 20, (3, 3))

eight = two.reshape(b-a+1, 1)

In [4]:
two

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
three

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [6]:
four

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
five

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
six

array([[0.2980329 , 0.03166154, 0.58309301],
       [0.13243208, 0.2636151 , 0.18840814],
       [0.47729287, 0.50530587, 0.35957655]])

In [9]:
seven

array([[16, 19, 19],
       [17, 14, 17],
       [12, 14, 13]], dtype=int32)

In [10]:
eight

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20]])

In [11]:
five + seven

array([[16., 19., 19.],
       [17., 14., 17.],
       [12., 14., 13.]])

In [12]:
five - seven

array([[-16., -19., -19.],
       [-17., -14., -17.],
       [-12., -14., -13.]])

In [13]:
six * seven

array([[ 4.76852645,  0.60156926, 11.07876718],
       [ 2.25134544,  3.69061138,  3.20293841],
       [ 5.72751443,  7.07428212,  4.6744951 ]])

In [14]:
np.cross(six, seven)

array([[-10.47719792,   3.666863  ,   5.15604052],
       [  1.84374269,   0.95159297,  -2.62740749],
       [  1.53490461,  -1.88988875,   0.61842978]])

In [15]:
seven

array([[16, 19, 19],
       [17, 14, 17],
       [12, 14, 13]], dtype=int32)

In [16]:
print(seven)
4 * seven

[[16 19 19]
 [17 14 17]
 [12 14 13]]


array([[64, 76, 76],
       [68, 56, 68],
       [48, 56, 52]], dtype=int32)

In [17]:
six

array([[0.2980329 , 0.03166154, 0.58309301],
       [0.13243208, 0.2636151 , 0.18840814],
       [0.47729287, 0.50530587, 0.35957655]])

In [20]:
six @ seven

array([[12.30388874, 14.26918885, 13.78108046],
       [ 8.86126773,  8.84453497,  9.44697212],
       [20.54180419, 21.17691829, 22.33325934]])

In [19]:
six.dot(seven)

array([[12.30388874, 14.26918885, 13.78108046],
       [ 8.86126773,  8.84453497,  9.44697212],
       [20.54180419, 21.17691829, 22.33325934]])