In [1]:
import numpy as np

In [2]:
v = np.array([10, 20, 30, 40])

In [3]:
print(v[0])
print(v[1:4])

10
[20 30 40]


In [74]:
x = np.array(np.linspace(10, 40, 31))
y = np.random.randint(1, 100, (31, 1))

In [71]:
x.shape

(31,)

In [75]:
y

array([[74],
       [71],
       [46],
       [ 2],
       [88],
       [64],
       [54],
       [36],
       [42],
       [56],
       [65],
       [22],
       [89],
       [85],
       [ 2],
       [82],
       [22],
       [88],
       [51],
       [14],
       [79],
       [ 1],
       [11],
       [78],
       [27],
       [26],
       [54],
       [67],
       [66],
       [ 6],
       [93]], dtype=int32)

In [77]:
x @ y

array([38182.])

x.dot(y)

L1 NORM - for v = [v1, v2, v3, v4, ..., vn], then L1 Norm = |v1|+|v2|...+|vn|

L2 NORM - L2 Norm --> if S = v1^2 + v2^2 + .... + vn^2, then L2 Norm = sqrt(S), same as |v|, or ||v||

L[inf] NORM ---> the L<inf> Norm is the Max value of |vi| for i = 1 to n.. , for example x = [-2, 76, -101], then L[inf] norm of x is 101

In [80]:
products = np.array([200, 150, 300, 250])
quantity = np.array([5, 2, 3, 4])
print(int(products.dot(quantity)))

3200


In [85]:
prd = np.array([500, 1200, 700])
qty = np.array([2, 1, 3])
print(prd @ qty, 0.9 * prd @ qty)

4300 3870.0


In [88]:
stk = np.array([50, 80, 120])
shr = np.array([10, 5, 2])
print(f'USD${stk @ shr}')
print(f'Rs. {83 * stk @ shr}')

USD$1140
Rs. 94620


In [93]:
print(sum([abs(i) for i in stk]))

250
