In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers


In [ ]:
print(f"Tensorflow version: {tf.__version__}")
print(f"Keras version: {keras.__version__}")

Tensorflow version: 2.21.0
Keras version: 3.15.1


In [3]:
print("Generating data")
x_train = np.random.random((1000000, 50)).astype('float32')
y_train = np.random.randint(2, size=(1000000, 1)).astype('float32')

print(f"X_train:\n{x_train}\n\n")
print(f"Y_train:\n{y_train}")

Generating data
X_train:
[[0.9416216  0.43000925 0.04578542 ... 0.03800529 0.43993166 0.2570943 ]
 [0.86616474 0.24610531 0.33199736 ... 0.18630363 0.33062696 0.55788815]
 [0.9513673  0.04833033 0.05183247 ... 0.19175814 0.78104216 0.4343027 ]
 ...
 [0.05667978 0.7137611  0.90658987 ... 0.17964509 0.6285696  0.92698926]
 [0.63926196 0.68037546 0.7249526  ... 0.4727669  0.8803876  0.5939278 ]
 [0.5512661  0.3872191  0.25853744 ... 0.57911885 0.7000976  0.6411386 ]]


Y_train:
[[0.]
 [0.]
 [1.]
 ...
 [0.]
 [1.]
 [0.]]


In [ ]:
print("BUILDING A SIMPLE NEURAL NETWORK")
model = keras.Sequential([
    layers.Input(shape=(50,)),
    layers.Dense(128, activation='leaky_relu'),
    layers.Dense(512, activation='gelu'),
    layers.Dense(1024, activation='leaky_relu'),
    layers.Dense(2048, activation='gelu'),
    layers.Dense(4096, activation='leaky_relu'),
    layers.Dense(2048, activation='leaky_relu'),
    layers.Dense(1024, activation='gelu'),
    layers.Dense(512, activation='leaky_relu'),
    layers.Dense(256, activation='gelu'),
    layers.Dense(128, activation='leaky_relu'),
    layers.Dense(1, activation='sigmoid')
])

BUILDING A SIMPLE NEURAL NETWORK


In [ ]:
keras.

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [15]:
print("TESTING THE MODEL TRAINING (fit)")
model.fit(x_train, y_train, epochs=5, batch_size=1024, verbose=1)

TESTING THE MODEL TRAINING (fit)
Epoch 1/5
977/977 ━━━━━━━━━━━━━━━━━━━━ 25s 19ms/step - accuracy: 0.4998 - loss: 0.7128
Epoch 2/5
977/977 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.5002 - loss: 0.6932
Epoch 3/5
977/977 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.5007 - loss: 0.6932
Epoch 4/5
977/977 ━━━━━━━━━━━━━━━━━━━━ 12s 12ms/step - accuracy: 0.4995 - loss: 0.6933
Epoch 5/5
977/977 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.5003 - loss: 0.6933
