In [1]:
import numpy as np
import scipy.stats as st

In [17]:
x = np.random.randint(10, 30, 40)

In [18]:
x

array([17, 20, 23, 20, 13, 18, 15, 13, 11, 14, 11, 21, 21, 14, 27, 17, 24,
       20, 13, 14, 24, 18, 11, 16, 13, 15, 24, 26, 12, 15, 29, 20, 22, 18,
       29, 18, 18, 18, 27, 22], dtype=int32)

In [19]:
n = len(x)

In [20]:
n

40

In [21]:
x_mean = x.mean()
SEM = x.std(ddof=1)/np.sqrt(n*1.0)

In [22]:
(x_mean - 1.645 * SEM, x_mean + 1.645*SEM)

(np.float64(17.194856897669922), np.float64(19.855143102330075))

In [23]:
(x_mean - st.norm.ppf(0.95,loc=0,scale=1)*SEM, x_mean + st.norm.ppf(0.95,loc=0,scale=1)*SEM)

(np.float64(17.194975254570146), np.float64(19.85502474542985))

In [24]:
st.norm.interval(0.9, loc=x_mean, scale=SEM)

(np.float64(17.194975254570142), np.float64(19.85502474542985))

In [27]:
(x_mean - st.t.ppf(0.995,df=n-1)*SEM, x_mean + st.t.ppf(0.995,df=n-1)*SEM)

(np.float64(16.335387815948522), np.float64(20.714612184051475))

In [28]:
st.t.interval(0.9995, df=n-1, loc=x_mean, scale=SEM)

(np.float64(15.454823877157516), np.float64(21.59517612284248))

In [29]:
st.t.interval(0.9999, df=n-1, loc=x_mean, scale=SEM)

(np.float64(15.021515187584768), np.float64(22.02848481241523))

## INTERVAL ESTIMATION OF PROPORTION

In [30]:
import numpy as np
import scipy.stats as st

1. There are two candidates for the election: A and B. The candidate A wants to survey his approval rating. Out of 100 surveyed, 55 answered positively. Can A be sure of this election?
   - Assume that A gets elected with 50% or more
   - Use 95% confidence interval

In [36]:
n_yes = 55
n_total = 100
p_mean = n_yes/n_total
SE = np.sqrt(p_mean*(1-p_mean)/n_total)
SE2 = np.sqrt(p_mean*(1-p_mean)/(n_total*10))

In [37]:
st.norm.interval(0.95, loc=p_mean, scale=SE)

(np.float64(0.45249302291006066), np.float64(0.6475069770899394))

=> *The confidence interval has the lower bound below 50%. So A cannot be sure with the confidence level of 95%*

In [35]:
print(st.norm.interval(0.99, loc=p_mean, scale=SE))
print(st.norm.interval(0.90, loc=p_mean, scale=SE))
print(st.norm.interval(0.70, loc=p_mean, scale=SE))

(np.float64(0.42185411014188756), np.float64(0.6781458898581125))
(np.float64(0.4681695652652013), np.float64(0.6318304347347987))
(np.float64(0.49843808990279237), np.float64(0.6015619100972077))


In [38]:
print(st.norm.interval(0.95, loc=p_mean, scale=SE2))

(np.float64(0.5191655864637935), np.float64(0.5808344135362066))


=> *The confidence interval has the lower bound above 50%. So A can be sure with the confidence level of 95%*

## INTERVAL ESTIMATION OF CORRELATION

In [39]:
import seaborn as sns

In [40]:
df = sns.load_dataset('iris')

In [41]:
df

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica


In [42]:
x = df['petal_length']
y = df['sepal_length']

In [43]:
np.round(st.pearsonr(x,y),3)

array([0.872, 0.   ])

In [45]:
x.corr(y)

np.float64(0.8717537758865831)

In [48]:
np.round(df.drop(columns=['species']).corr(),3)

,sepal_length,sepal_width,petal_length,petal_width
sepal_length,1.000,-0.118,0.872,0.818
sepal_width,-0.118,1.000,-0.428,-0.366
petal_length,0.872,-0.428,1.000,0.963
petal_width,0.818,-0.366,0.963,1.000


In [49]:
np.round(st.spearmanr(x,y),3)

array([0.882, 0.   ])

In [50]:
np.round(st.kendalltau(x,y),3)

array([0.719, 0.   ])

In [51]:
n = len(x)
r = x.corr(y)
z = np.arctanh(r)
std_error_z = 1/np.sqrt(n-3)

In [52]:
{'low': np.tanh(z-st.norm.ppf(0.975)*std_error_z), 'high': np.tanh(z+st.norm.ppf(0.975)*std_error_z)}

{'low': np.float64(0.8270363296643621), 'high': np.float64(0.9055080488214541)}

In [53]:
{'low': np.tanh(z-st.norm.ppf(0.995)*std_error_z), 'high': np.tanh(z+st.norm.ppf(0.995)*std_error_z)}

{'low': np.float64(0.8102954422392553), 'high': np.float64(0.9142447161982906)}