In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [4]:
arr1 = np.array([2*i+1 for i in range(5)])

In [5]:
arr2 = np.array([2*i+1 for i in range(5)])

In [6]:
id(arr1)

2195996967728

In [7]:
id(arr2)

2195996980304

In [8]:
arr3 = arr1

In [9]:
id(arr3)

2195996967728

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(10, 20, 3)

array([10, 13, 16, 19])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [19]:
arr = np.linspace(0, 10, 5, retstep=True)

In [21]:
arr[0]

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
arr[1]

np.float64(2.5)

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.zeros(5, dtype='int64')

array([0, 0, 0, 0, 0])

In [27]:
np.zeros(5, dtype='int64').dtype

dtype('int64')

In [28]:
arr = np.ones((2, 3), dtype='int_')

In [29]:
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [30]:
arr.dtype

dtype('int64')

In [31]:
arr.astype('float32')

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [33]:
srr1 = np.array([111, 2.3, True, False, False])

In [35]:
srr1

array([111. ,   2.3,   1. ,   0. ,   0. ])

In [36]:
arr2 = np.array([111, 2.3, 'python', 'abc'])

In [37]:
arr2

array(['111', '2.3', 'python', 'abc'], dtype='<U32')