In [1]:
import numpy as np

In [9]:
a = np.array([0,1,2,3])
b = np.array([[x+4*i for x in range(4)] for i in range(4)])

In [10]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
a1 = np.array([10*i for i in range(6)])

In [12]:
a1[5] = 70

In [13]:
a1

array([ 0, 10, 20, 30, 40, 70])

In [15]:
a1[[1, 3, 4]]

array([10, 30, 40])

In [20]:
a2 = np.arange(10, 100, 10).reshape(3, 3)

In [21]:
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [22]:
a2.T

array([[10, 40, 70],
       [20, 50, 80],
       [30, 60, 90]])

In [27]:
a2.T[[0,1],[0, 2]]

array([10, 80])

In [40]:
def is_prime(n: int):
    if (n <= 1):
        return False
    for i in range(2, 1+int(n**0.5)):
        if n%i==0:
            return False
    return True

In [41]:
a3 = np.arange(1, 101, 1)
v_is_prime = np.vectorize(is_prime)

In [42]:
a3[v_is_prime(a3)]

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97])

In [43]:
x = np.arange(1, 101).reshape(10, 10)

In [44]:
x

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [51]:
x[5:, 5:]

array([[ 56,  57,  58,  59,  60],
       [ 66,  67,  68,  69,  70],
       [ 76,  77,  78,  79,  80],
       [ 86,  87,  88,  89,  90],
       [ 96,  97,  98,  99, 100]])

In [52]:
names = np.array(['Bob', 'Joe', 'Tom', 'Bob', 'Tom', 'Joe', 'Joe'])

In [55]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [57]:
names[names=='Bob']

array(['Bob', 'Bob'], dtype='<U3')

In [80]:
# fancy indexing
np.empty((8,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [78]:
np.empty((10, 45))

array([[1.41470487e-311, 1.41470487e-311, 1.41470487e-311,
        1.41470487e-311, 1.41470488e-311, 1.41470487e-311,
        1.41470488e-311, 1.41470488e-311, 1.41470488e-311,
        1.41470487e-311, 1.41470488e-311, 1.41470488e-311,
        1.41470488e-311, 1.41470487e-311, 1.41470487e-311,
        1.41470488e-311, 1.41470488e-311, 1.41470487e-311,
        1.41470488e-311, 1.41470487e-311, 1.41470487e-311,
        1.41470488e-311, 1.41470488e-311, 1.41470487e-311,
        1.41470488e-311, 1.41470487e-311, 1.41470488e-311,
        1.41470487e-311, 1.41470488e-311, 1.41470488e-311,
        1.41470488e-311, 1.41470487e-311, 1.41470488e-311,
        1.41470487e-311, 1.41470487e-311, 1.41470487e-311,
        1.41470488e-311, 1.41470488e-311, 1.41470487e-311,
        1.41470488e-311, 1.41470487e-311, 1.41470488e-311,
        1.41470487e-311, 1.41470487e-311, 1.41470487e-311],
       [1.41470487e-311, 1.41470488e-311, 1.41470488e-311,
        1.41470487e-311, 1.41470487e-311, 1.41470466e-3

In [81]:
h = np.arange(18).reshape(2, 3, 3)

In [82]:
h

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [88]:
h.transpose((1, 2, 0))

array([[[ 0,  9],
        [ 1, 10],
        [ 2, 11]],

       [[ 3, 12],
        [ 4, 13],
        [ 5, 14]],

       [[ 6, 15],
        [ 7, 16],
        [ 8, 17]]])

In [89]:
a = np.arange(10)
b = a.reshape(2, 5)

In [90]:
a[0] = -999

In [91]:
b

array([[-999,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [92]:
c = a.reshape(2, 5).copy()
c[0,0] = 0

In [93]:
a

array([-999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [94]:
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [95]:
a = np.array([[1, 2], [3, 4]])
b = np.append(a, [[9, 9]], axis=0)

In [96]:
b

array([[1, 2],
       [3, 4],
       [9, 9]])

In [97]:
c = np.append(a, [[9], [9]], axis=1)

In [98]:
c

array([[1, 2, 9],
       [3, 4, 9]])

In [99]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.delete(a, 0)

array([2, 3, 4, 5, 6])

In [100]:
np.delete(a, (0, 2, 4))

array([2, 4, 6])

In [101]:
np.delete(a, 0, axis=0)

array([[4, 5, 6]])

In [102]:
np.delete(a, 1, axis=1)

array([[1, 3],
       [4, 6]])